<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage3.master" AutoEventWireup="true" CodeFile="AdminForums.aspx.cs" Inherits="AdminForums" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server" >
    <asp:GridView ID="gridforum" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" OnRowDeleting="gridforum_RowDeleting">
        <Columns>
            <asp:TemplateField Visible="false">
                <ItemTemplate>
                   <asp:Label ID="lblqid" runat="server" Text='<%#Eval("ReplyId") %>'></asp:Label></ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Question">
                <ItemTemplate>
                    <%#Eval("Question") %>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Reply">
                <ItemTemplate><%#Eval("Reply") %></ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="PostedBy">
                <ItemTemplate><%#Eval("UserName") %></ItemTemplate>
            </asp:TemplateField>
            <%--<asp:TemplateField>
                <ItemTemplate>
                    <asp:LinkButton ID="linkdelete" runat="server" Text="Delete" CommandName="delete"></asp:LinkButton>
                </ItemTemplate>
            </asp:TemplateField>
            --%>
        </Columns>
    </asp:GridView>
    <asp:Label ID="lblmsg" runat="server"></asp:Label>
</asp:Content>

