<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage3.master" AutoEventWireup="true" CodeFile="AdminProjects.aspx.cs" Inherits="AdminProjects" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:GridView ID="gridprojects" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" OnRowDeleting="gridprojects_RowDeleting">
        <Columns>
            <asp:TemplateField>
                <ItemTemplate>
                    <asp:Label ID="lblid" runat="server" Visible="false" Text='<%#Eval("ProjectId") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="ProjectType">
                <ItemTemplate><asp:Label ID="lbltype" runat="server" Text='<%#Eval("ProjectType") %>'></asp:Label></ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="FileName">
                <ItemTemplate><asp:Label ID="lblname" runat="server" Text='<%#Eval("FileName") %>'></asp:Label></ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="FileType">
                <ItemTemplate><asp:Label ID="lblfiletype" runat="server" Text='<%#Eval("FileType") %>'></asp:Label></ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="PostedBy">
                <ItemTemplate>
                    <asp:Label ID="lbluname" runat="server" Text='<%#Eval("UserName") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField>
                <ItemTemplate>
                    <asp:LinkButton ID="linkdownload" runat="server" Text="DownLoad" CommandName="Download"></asp:LinkButton>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
    <asp:Label ID="lblmsg" runat="server"></asp:Label>
</asp:Content>

